name: love_station
description: "Trạm Sạc Tình Yêu cho Gấu và Bé Trắng"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  firebase_core: ^3.12.0
  firebase_database: ^11.3.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  marquee: ^2.2.3
  vibration: ^3.1.8
  path_provider: ^2.1.2
  web_haptics: ^0.0.1
  peanut: ^6.0.1
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/gau_bong.png
    - assets/be_trang.png
    - assets/music/
    - assets/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/NotoSans-Regular.ttf