name: love_station
description: "Trạm Sạc Tình Yêu cho Gấu và Bé Trắng"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Các gói cần thiết để chạy tính năng âm thanh, database và hiệu ứng
  audioplayers: ^5.2.1
  firebase_core: ^2.24.0
  firebase_database: ^10.4.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  marquee: ^2.2.3
  vibration: ^2.0.1  # Thêm dòng này để điều khiển rung
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Hình ảnh nền và avatar
    - assets/