name: heart_app
description: "A new Flutter project for love."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true

  # PHẦN THÊM HÌNH NỀN CỦA BẠN Ở ĐÂY
  assets:
    - assets/
    - assets/background.jpg
    - assets/hello.mp3
    - assets/sleep.mp3