import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by FlutterFire CLI.
/// Replace placeholder values with your actual Firebase Web/Android/iOS app config.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3a5Yjs2knhSsk1sK4oB8sfUPqzi66b1g',
    authDomain: 'meove-53c46.firebaseapp.com',
    databaseURL: 'https://meove-53c46-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'meove-53c46',
    storageBucket: 'meove-53c46.firebasestorage.app',
    messagingSenderId: '977041101576',
    appId: '1:977041101576:web:4b7a33894f5a0b17ff92bd',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3a5Yjs2knhSsk1sK4oB8sfUPqzi66b1g',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '977041101576',
    projectId: 'meove-53c46',
    storageBucket: 'meove-53c46.firebasestorage.app',
    databaseURL: 'https://meove-53c46-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3a5Yjs2knhSsk1sK4oB8sfUPqzi66b1g',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '977041101576',
    projectId: 'meove-53c46',
    storageBucket: 'meove-53c46.firebasestorage.app',
    databaseURL: 'https://meove-53c46-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3a5Yjs2knhSsk1sK4oB8sfUPqzi66b1g',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '977041101576',
    projectId: 'meove-53c46',
    storageBucket: 'meove-53c46.firebasestorage.app',
    databaseURL: 'https://meove-53c46-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );
}
